main = ".open-next/worker.js"
name = "aimarker"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
minify = true
workers_dev = true

# Define routes for frontend and API
routes = [
  # Frontend route
  { pattern = "aimarker.tech", custom_domain = true },
  
  # API routes
  { pattern = "api.aimarker.tech/*", custom_domain = true }
]

# Assets configuration
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# KV namespaces for caching and rate limiting
[[kv_namespaces]]
binding = "CACHE"
id = "83611685737d48fc8e64205e47c7a27f"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "a61a73d62e9740e4bb02bbd8dc97c03e"

# R2 buckets for storage
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "aimarker-storage"

[[r2_buckets]]
binding = "CACHE_BUCKET"
bucket_name = "aimarker-cache"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_SUPABASE_URL = "https://tqlnqqrrpzmdpgijxiqk.supabase.co"
OCR_SERVICE_ENDPOINT = "https://ocr.aimarker.tech"  # Cloudflare Tunnel endpoint

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "preview"
NEXT_PUBLIC_SUPABASE_URL = "https://tqlnqqrrpzmdpgijxiqk.supabase.co"
OCR_SERVICE_ENDPOINT = "https://ocr.aimarker.tech"  # Cloudflare Tunnel endpoint

# Secrets (use wrangler secret put command)
# Required secrets:
# - NEXT_PUBLIC_SUPABASE_ANON_KEY
# - SUPABASE_SERVICE_ROLE_KEY
# - DATABASE_URL
# - STACK_SECRET_SERVER_KEY
# - UPSTASH_REDIS_REST_URL
# - UPSTASH_REDIS_REST_TOKEN
# - OPENROUTER_API_KEY
# - STRIPE_SECRET_KEY
# - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
# - OCR_SERVICE_API_KEY  # New secret for OCR service authentication
# - SENTRY_DSN (optional)
# - SENTRY_AUTH_TOKEN (optional)
#
# Set secrets using: wrangler secret put SECRET_NAME